### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by Revadike** [ZeroUnderscoreOu/SteamBBCodes#1]
Please disable these alerts:
![](https://camo.githubusercontent.com/5aa14e15ae7fa5edebe7b7bab72290dd55799c26/68747470733a2f2f692e696d6775722e636f6d2f4c34437a4d586c2e706e67)

**Comment by ZeroUnderscoreOu** [comment]
@Royalgamer06 I intentionally set up those alerts for users to report pages, which should be excluded.
Though just a few did. I'll disable them in the next update.

**Comment by Revadike** [comment]
You can put them in console. But no alerts please. Thanks

**Comment by ZeroUnderscoreOu** [comment]
You probably can imagine yourself how many players would bother checking the console, if even with alerts I got messages form just a handful of them.
Anyway, enjoy d4424d2.
